services:
  storage: 
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: libs
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 4002:4002
    environment:
      - COUNTER_PORT=4002
      - REDIS_URL=redis://storage
    command: npm run counter-start
    depends_on:
      - storage
  libs:
    image: libs
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 80:3002
    environment:
      - PORT=3002
      - COUNTER_URL=http://counter:4002
    command: npm run start
    depends_on:
      - counter
      - storage
