services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
  libs:
    image: libs
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 80:3002
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://mongo:27017
    command: npm run dev
    depends_on:
      - mongo
